Rails.application.routes.draw do
  root to: "pages#home"
  get "gallery", to: "pages#gallery"
  get "about", to: "pages#about"
  get "services", to: "pages#services"
  get "contact", to: "pages#contact"
  get "daisy", to: "pages#daisy"
  get "elizabeth", to: "pages#elizabeth"
  get "rosie", to: "pages#rosie"
  get "emily", to: "pages#emily"
  get "juliette", to: "pages#juliette"
  get "mara", to: "pages#mara"
  get "jefi", to: "pages#jefi"
  get "sunita", to: "pages#sunita"
  get "samalegra", to: "pages#samalegra"
  get "samantha", to: "pages#samantha"
  get "willie", to: "pages#willie"
  get "britt", to: "pages#britt"
  get "sam", to: "pages#sam"
  get "lique", to: "pages#lique"
  get "duneisle", to: "pages#duneisle"
  get "alina", to: "pages#alina"
  get "marga", to: "pages#marga"
  get "meeslateesha", to: "pages#meeslateesha"
  get "isis", to: "pages#isis"
  get "maudy", to: "pages#maudy"
  get "robinlisa", to: "pages#robinlisa"
end
